<?php
namespace Neducatio\ORMSessionHandlerBundle\Model;

use Doctrine\ORM\Mapping as ORM;

/**
 * Session Class Base
 *
 * @ORM\MappedSuperclass
 */
abstract class Session
{
    /**
     * Session id (generated by PHP)
     *
     * @ORM\Id
     * @ORM\Column(name="id", type="string")
     */
    protected $id;

    /**
     * @ORM\Column(name="timestamp", type="integer", nullable=true)
     */
    protected $timestamp;

    /**
     * Session data (based64-encoded serialized $_SESSION global array)
     *
     * @ORM\Column(name="data", type="text", nullable=true)
     */
    protected $data;

    /**
     * Constructor
     *
     * @param string $id session id
     */
    public function __construct($id)
    {
        $this->id = $id;
    }

    /**
     * Get Session ID
     *
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set session's data
     *
     * @param string $data
     */
    public function setData($data, $updateTimestamp = true)
    {
        $this->data = base64_encode($data);

        if ($updateTimestamp) {
            $this->updateTimestamp();
        }
    }

    /**
     * Set session's data
     *
     * @return string
     */
    public function getData()
    {
        return base64_decode($this->data);
    }

    /**
     * Update session's timestamp
     */
    public function updateTimestamp()
    {
        $this->timestamp = time();
    }

    /**
     * Get timestamp
     *
     * @return integer
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }
}